### ISSUE TITLE
Hide Empty Links Edge Case Error

### ISSUE THREAD

**Issue by QuinnHerden** [therden/sequential-links-rustler#20]
- Use example mask `https://therden.github.io/sequential-links-rustler/images/sausage{0-20}.jpeg`
- Deselect the "Hide empty links (images only)" box
- Click "Rustle Up Some Links"

Python prints:
```
Traceback (most recent call last):
  File "slr.py", line 127, in <module>
    do_it(
  File "E:\repos\sequential-links-rustler\main.py", line 219, in make_and_open_HTML_file_from_URL_mask
    URL = get_HTML_file(
  File "E:\repos\sequential-links-rustler\main.py", line 151, in get_HTML_file
    style = f"<style>img {width: {thumbsize}; padding: 5x; position: relative; visibility: visible; display: inline}</style>"
NameError: name 'width' is not defined
```

**Comment by therden** [comment]
Thanks for the bug report, @QuinnHerden!

This bug is squashed, and Issue closed.
